version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/NewsManagementSystem.BusinessObject"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/NewsManagementSystem.DataAccess"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/NewsManagementSystem.Services"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/NewsManagementSystem.WebMVC"
    schedule:
      interval: "daily"
