version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./entrypoint-init.sql:/tmp/entrypoint-init.sql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  db-seed:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./entrypoint-init.sql:/entrypoint-init.sql
    entrypoint: [ "/bin/bash", "-c", "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S db -U sa -P Your_password123 -i /entrypoint-init.sql" ]

  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5215:8080"
    depends_on:
      db-seed:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FUNewsManagement;User Id=sa;Password=Your_password123;TrustServerCertificate=True;

volumes:
  sql_data:
